services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  api:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: alarm_user
      DB_PASSWORD: alarm_password
      DB_NAME: alarm_platform
      PORT: 4000
    ports:
      - "4001:4000"

volumes:
  db-data:
